# Generated by Django 5.2.8 on 2025-11-21 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, help_text='Término o sigla permitida (ej: "igac", "acm", "netapp")', max_length=100, unique=True, verbose_name='Término/Sigla')),
                ('value', models.TextField(help_text='Significado completo del término (ej: "instituto geográfico agustín codazzi")', verbose_name='Descripción/Significado')),
                ('is_active', models.BooleanField(default=True, help_text='Si está desactivado, el término no se validará', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dictionary_entries_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dictionary_entries_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Entrada del Diccionario',
                'verbose_name_plural': 'Entradas del Diccionario',
                'ordering': ['key'],
                'indexes': [models.Index(fields=['key', 'is_active'], name='dictionary__key_26047c_idx'), models.Index(fields=['is_active', 'created_at'], name='dictionary__is_acti_7b5373_idx')],
            },
        ),
    ]
