# Generated by Django 4.2.16 on 2026-01-04 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIGeneratedAbbreviation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_word', models.CharField(db_index=True, help_text='Palabra completa normalizada (ej: "prestacion")', max_length=100, unique=True, verbose_name='Palabra Original')),
                ('abbreviation', models.CharField(db_index=True, help_text='Abreviación generada (ej: "prest")', max_length=20, verbose_name='Abreviación')),
                ('times_used', models.PositiveIntegerField(default=1, help_text='Número de veces que se ha usado esta abreviación', verbose_name='Veces usado')),
                ('status', models.CharField(choices=[('pending', 'Pendiente de revisión'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('corrected', 'Corregido manualmente')], db_index=True, default='pending', max_length=20, verbose_name='Estado')),
                ('original_ai_abbreviation', models.CharField(blank=True, help_text='Si fue corregido, aquí se guarda lo que la IA generó originalmente', max_length=20, null=True, verbose_name='Abreviación original IA')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('last_used_at', models.DateTimeField(auto_now=True, verbose_name='Último uso')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de revisión')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abbreviations_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por')),
            ],
            options={
                'verbose_name': 'Abreviación Generada por IA',
                'verbose_name_plural': 'Abreviaciones Generadas por IA',
                'ordering': ['-times_used', 'original_word'],
                'indexes': [models.Index(fields=['original_word'], name='dictionary__origina_2285f6_idx'), models.Index(fields=['abbreviation'], name='dictionary__abbrevi_baf25d_idx'), models.Index(fields=['status', 'times_used'], name='dictionary__status_959107_idx')],
            },
        ),
    ]
