# Generated by Django 4.2.16 on 2026-01-01 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrashItem',
            fields=[
                ('trash_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_name', models.CharField(help_text='Nombre original del archivo o directorio', max_length=255)),
                ('original_path', models.TextField(help_text='Ruta completa original (relativa al repositorio)')),
                ('is_directory', models.BooleanField(default=False, help_text='True si era un directorio (se almacena como .tar.gz)')),
                ('size_bytes', models.BigIntegerField(default=0, help_text='Tamaño en bytes del archivo o directorio')),
                ('file_count', models.IntegerField(default=1, help_text='Cantidad de archivos (1 para archivos, N para directorios)')),
                ('dir_count', models.IntegerField(default=0, help_text='Cantidad de subdirectorios (solo para directorios)')),
                ('file_hash', models.CharField(blank=True, help_text='Hash SHA256 del contenido para verificar integridad', max_length=64, null=True)),
                ('mime_type', models.CharField(blank=True, help_text='Tipo MIME del archivo', max_length=100, null=True)),
                ('extension', models.CharField(blank=True, help_text='Extensión del archivo original', max_length=50, null=True)),
                ('deleted_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de eliminación')),
                ('expires_at', models.DateTimeField(help_text='Fecha y hora de expiración automática')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('storing', 'Almacenando'), ('stored', 'Almacenado'), ('restoring', 'Restaurando'), ('restored', 'Restaurado'), ('expired', 'Expirado'), ('error', 'Error')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text="Mensaje de error si status='error'", null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Información adicional (permisos, propietario original, etc.)')),
                ('restored_at', models.DateTimeField(blank=True, help_text='Fecha de restauración (si fue restaurado)', null=True)),
                ('restored_path', models.TextField(blank=True, help_text='Ruta donde se restauró (si difiere de la original)', null=True)),
                ('deleted_by', models.ForeignKey(help_text='Usuario que eliminó el archivo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trash_items', to=settings.AUTH_USER_MODEL)),
                ('restored_by', models.ForeignKey(blank=True, help_text='Usuario que restauró el archivo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restored_trash_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item de Papelera',
                'verbose_name_plural': 'Items de Papelera',
                'db_table': 'trash_items',
                'ordering': ['-deleted_at'],
            },
        ),
        migrations.CreateModel(
            name='TrashShareLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('permission', models.CharField(choices=[('download', 'Solo descarga'), ('preview', 'Vista previa')], default='download', max_length=20)),
                ('password_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('require_email', models.BooleanField(default=False)),
                ('max_downloads', models.IntegerField(blank=True, null=True)),
                ('download_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('trash_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='trash.trashitem')),
            ],
            options={
                'db_table': 'trash_share_links',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='trashitem',
            index=models.Index(fields=['original_path'], name='trash_items_origina_5634c7_idx'),
        ),
        migrations.AddIndex(
            model_name='trashitem',
            index=models.Index(fields=['original_name'], name='trash_items_origina_442ea0_idx'),
        ),
        migrations.AddIndex(
            model_name='trashitem',
            index=models.Index(fields=['deleted_by'], name='trash_items_deleted_ac37ef_idx'),
        ),
        migrations.AddIndex(
            model_name='trashitem',
            index=models.Index(fields=['deleted_at'], name='trash_items_deleted_90d9b8_idx'),
        ),
        migrations.AddIndex(
            model_name='trashitem',
            index=models.Index(fields=['expires_at'], name='trash_items_expires_2b60c2_idx'),
        ),
        migrations.AddIndex(
            model_name='trashitem',
            index=models.Index(fields=['status'], name='trash_items_status_48263b_idx'),
        ),
        migrations.AddIndex(
            model_name='trashitem',
            index=models.Index(fields=['is_directory'], name='trash_items_is_dire_227d09_idx'),
        ),
    ]
