# Generated by Django 4.2.16 on 2026-01-01 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trash', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrashShareLink',
        ),
    ]
