# Generated by Django 4.2.16 on 2026-01-02 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trash', '0002_add_trash_item_to_sharelink'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrashConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_size_gb', models.DecimalField(decimal_places=2, default=5.0, help_text='Tamaño máximo de la papelera en GB', max_digits=10)),
                ('retention_days', models.IntegerField(default=30, help_text='Días de retención de archivos en papelera')),
                ('auto_cleanup_enabled', models.BooleanField(default=True, help_text='Habilitar limpieza automática de archivos expirados')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, help_text='Último usuario que modificó la configuración', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trash_config_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Papelera',
                'verbose_name_plural': 'Configuración de Papelera',
                'db_table': 'trash_config',
            },
        ),
    ]
