# Generated by Django 4.2.16 on 2026-01-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash', '0003_add_trash_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='trashconfig',
            name='max_item_size_gb',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Tamaño máximo por archivo/directorio individual en GB (archivos mayores se eliminan sin respaldo)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='trashconfig',
            name='max_size_gb',
            field=models.DecimalField(decimal_places=2, default=2048.0, help_text='Tamaño máximo total de la papelera en GB', max_digits=10),
        ),
    ]
