# Generated by Django 4.2.16 on 2026-01-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash', '0004_add_max_item_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='trashitem',
            name='notified_3days',
            field=models.BooleanField(default=False, help_text='Si ya se notificó al usuario 3 días antes de expirar'),
        ),
        migrations.AddField(
            model_name='trashitem',
            name='notified_7days',
            field=models.BooleanField(default=False, help_text='Si ya se notificó al usuario 7 días antes de expirar'),
        ),
    ]
