# Generated by Django 5.2.8 on 2025-11-24 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroqAPIKeyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_identifier', models.CharField(help_text='Identificador único de la key (ej: key_1, key_2, etc.)', max_length=50, unique=True)),
                ('key_name', models.CharField(blank=True, help_text="Nombre descriptivo opcional (ej: 'Cuenta Gmail Principal')", max_length=100, null=True)),
                ('total_calls', models.PositiveIntegerField(default=0, help_text='Total de llamadas realizadas con esta key')),
                ('successful_calls', models.PositiveIntegerField(default=0, help_text='Llamadas exitosas')),
                ('failed_calls', models.PositiveIntegerField(default=0, help_text='Llamadas fallidas')),
                ('rate_limit_errors', models.PositiveIntegerField(default=0, help_text='Número de veces que alcanzó el rate limit')),
                ('total_tokens_used', models.PositiveIntegerField(default=0, help_text='Total de tokens consumidos')),
                ('is_active', models.BooleanField(default=True, help_text='Si la key está activa o deshabilitada manualmente')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Última vez que se usó esta key', null=True)),
                ('last_error_at', models.DateTimeField(blank=True, help_text='Última vez que ocurrió un error', null=True)),
                ('last_rate_limit_at', models.DateTimeField(blank=True, help_text='Última vez que alcanzó el rate limit', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Groq API Key Usage',
                'verbose_name_plural': 'Groq API Keys Usage',
                'db_table': 'groq_api_key_usage',
                'ordering': ['key_identifier'],
            },
        ),
    ]
