# Generated by Django 4.2.16 on 2026-01-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groq_stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groqapikeyusage',
            name='is_restricted',
            field=models.BooleanField(default=False, help_text='Si la organización está restringida por GROQ'),
        ),
        migrations.AddField(
            model_name='groqapikeyusage',
            name='last_error_message',
            field=models.CharField(blank=True, help_text='Último mensaje de error', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='groqapikeyusage',
            name='last_reset_date',
            field=models.DateField(blank=True, help_text='Fecha del último reset de contadores', null=True),
        ),
        migrations.AddField(
            model_name='groqapikeyusage',
            name='last_success_at',
            field=models.DateTimeField(blank=True, help_text='Última llamada exitosa', null=True),
        ),
        migrations.AddField(
            model_name='groqapikeyusage',
            name='restriction_errors',
            field=models.PositiveIntegerField(default=0, help_text='Errores de restricción de organización (400)'),
        ),
        migrations.AlterField(
            model_name='groqapikeyusage',
            name='failed_calls',
            field=models.PositiveIntegerField(default=0, help_text='Llamadas fallidas (hoy)'),
        ),
        migrations.AlterField(
            model_name='groqapikeyusage',
            name='rate_limit_errors',
            field=models.PositiveIntegerField(default=0, help_text='Número de veces que alcanzó el rate limit (hoy)'),
        ),
        migrations.AlterField(
            model_name='groqapikeyusage',
            name='successful_calls',
            field=models.PositiveIntegerField(default=0, help_text='Llamadas exitosas (hoy)'),
        ),
        migrations.AlterField(
            model_name='groqapikeyusage',
            name='total_calls',
            field=models.PositiveIntegerField(default=0, help_text='Total de llamadas realizadas con esta key (hoy)'),
        ),
        migrations.AlterField(
            model_name='groqapikeyusage',
            name='total_tokens_used',
            field=models.PositiveIntegerField(default=0, help_text='Total de tokens consumidos (hoy)'),
        ),
    ]
