# Generated by Django 4.2.16 on 2026-01-02 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='Asunto')),
                ('thread_type', models.CharField(choices=[('warning', 'Advertencia/Llamado de atención'), ('info', 'Información'), ('support', 'Soporte')], default='info', max_length=20, verbose_name='Tipo')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Cerrado')),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_unread_count', models.IntegerField(default=0)),
                ('user_unread_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_message_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(help_text='Admin que inició la conversación', on_delete=django.db.models.deletion.CASCADE, related_name='admin_threads', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_threads', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='Usuario destinatario', on_delete=django.db.models.deletion.CASCADE, related_name='user_threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hilo de conversación',
                'verbose_name_plural': 'Hilos de conversación',
                'db_table': 'notification_threads',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('notification_type', models.CharField(choices=[('system', 'Sistema'), ('trash_expiry', 'Expiración Papelera'), ('permission_expiry', 'Expiración Permiso'), ('path_renamed', 'Ruta Renombrada'), ('admin_message', 'Mensaje Admin'), ('warning', 'Advertencia'), ('info', 'Información')], default='warning', max_length=20)),
                ('subject', models.CharField(max_length=200, verbose_name='Asunto')),
                ('message', models.TextField(help_text='Usa {variable} para campos dinámicos', verbose_name='Mensaje')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plantilla de notificación',
                'verbose_name_plural': 'Plantillas de notificación',
                'db_table': 'notification_templates',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('system', 'Sistema'), ('trash_expiry', 'Expiración Papelera'), ('permission_expiry', 'Expiración Permiso'), ('path_renamed', 'Ruta Renombrada'), ('admin_message', 'Mensaje Admin'), ('warning', 'Advertencia'), ('info', 'Información')], default='info', max_length=20, verbose_name='Tipo')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('normal', 'Normal'), ('high', 'Alta'), ('urgent', 'Urgente')], default='normal', max_length=10, verbose_name='Prioridad')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('related_path', models.TextField(blank=True, null=True, verbose_name='Ruta relacionada')),
                ('related_object_type', models.CharField(blank=True, help_text='Tipo de objeto: trash_item, permission, etc.', max_length=50, null=True)),
                ('related_object_id', models.CharField(blank=True, help_text='ID del objeto relacionado', max_length=100, null=True)),
                ('action_url', models.CharField(blank=True, help_text='URL para acción (ej: /trash, /my-permissions)', max_length=200, null=True)),
                ('is_read', models.BooleanField(default=False, verbose_name='Leído')),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False, verbose_name='Archivado')),
                ('email_sent', models.BooleanField(default=False, verbose_name='Email enviado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expira')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinatario')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Remitente')),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='notifications.messagethread')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_583549_idx'), models.Index(fields=['recipient', 'is_archived'], name='notificatio_recipie_d51e24_idx'), models.Index(fields=['recipient', 'created_at'], name='notificatio_recipie_2c3905_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_19df93_idx'), models.Index(fields=['thread'], name='notificatio_thread__44769c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='messagethread',
            index=models.Index(fields=['admin', 'is_closed'], name='notificatio_admin_i_727651_idx'),
        ),
        migrations.AddIndex(
            model_name='messagethread',
            index=models.Index(fields=['user', 'is_closed'], name='notificatio_user_id_575cd0_idx'),
        ),
        migrations.AddIndex(
            model_name='messagethread',
            index=models.Index(fields=['last_message_at'], name='notificatio_last_me_6b3afe_idx'),
        ),
    ]
