# Generated by Django 4.2.16 on 2026-01-02 22:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import notifications.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0002_add_messaging_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=notifications.models.message_attachment_path, verbose_name='Archivo')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Nombre original')),
                ('file_type', models.CharField(choices=[('image', 'Imagen'), ('video', 'Video'), ('document', 'Documento'), ('other', 'Otro')], default='other', max_length=20, verbose_name='Tipo de archivo')),
                ('mime_type', models.CharField(blank=True, default='', max_length=100, verbose_name='MIME Type')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='Tamaño (bytes)')),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='message_attachments/thumbnails/', verbose_name='Miniatura')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Adjunto de mensaje',
                'verbose_name_plural': 'Adjuntos de mensajes',
                'db_table': 'message_attachments',
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('system', 'Sistema'), ('trash_expiry', 'Expiración Papelera'), ('permission_expiry', 'Expiración Permiso'), ('path_renamed', 'Ruta Renombrada'), ('admin_message', 'Mensaje Admin'), ('user_message', 'Mensaje de Usuario'), ('support_ticket', 'Ticket de Soporte'), ('warning', 'Advertencia'), ('info', 'Información')], default='info', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='notification_type',
            field=models.CharField(choices=[('system', 'Sistema'), ('trash_expiry', 'Expiración Papelera'), ('permission_expiry', 'Expiración Permiso'), ('path_renamed', 'Ruta Renombrada'), ('admin_message', 'Mensaje Admin'), ('user_message', 'Mensaje de Usuario'), ('support_ticket', 'Ticket de Soporte'), ('warning', 'Advertencia'), ('info', 'Información')], default='warning', max_length=20),
        ),
        migrations.AddIndex(
            model_name='messagethread',
            index=models.Index(fields=['participant_1', 'is_closed'], name='notificatio_partici_c83bba_idx'),
        ),
        migrations.AddIndex(
            model_name='messagethread',
            index=models.Index(fields=['participant_2', 'is_closed'], name='notificatio_partici_90f7ef_idx'),
        ),
        migrations.AddIndex(
            model_name='messagethread',
            index=models.Index(fields=['thread_type'], name='notificatio_thread__c3a31a_idx'),
        ),
        migrations.AddIndex(
            model_name='messagethread',
            index=models.Index(fields=['assigned_to'], name='notificatio_assigne_1c47c0_idx'),
        ),
        migrations.AddField(
            model_name='messageattachment',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='notifications.notification', verbose_name='Mensaje'),
        ),
        migrations.AddField(
            model_name='messageattachment',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='messageattachment',
            index=models.Index(fields=['notification'], name='message_att_notific_947a0c_idx'),
        ),
        migrations.AddIndex(
            model_name='messageattachment',
            index=models.Index(fields=['file_type'], name='message_att_file_ty_59223d_idx'),
        ),
    ]
