# Generated by Django 4.2.16 on 2026-01-04 07:24

import django.core.files.storage
from django.db import migrations, models
import notifications.models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_add_message_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageattachment',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/nas-attachments/', location='/mnt/repositorio/2510SP/H_Informacion_Consulta/Sub_Proy/04_bk/trans_doc_platform/message_attachments'), upload_to=notifications.models.message_attachment_path, verbose_name='Archivo'),
        ),
    ]
