# Generated by Django 4.2.16 on 2025-12-31 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, editable=False, max_length=64, unique=True)),
                ('path', models.CharField(help_text='Ruta en NetApp', max_length=1000)),
                ('is_directory', models.BooleanField(default=False)),
                ('permission', models.CharField(choices=[('view', 'Solo ver'), ('download', 'Ver y descargar')], default='view', max_length=20)),
                ('password', models.CharField(blank=True, help_text='Contraseña opcional (hasheada)', max_length=128, null=True)),
                ('require_email', models.BooleanField(default=False, help_text='Requiere que el usuario ingrese su email')),
                ('allowed_domain', models.CharField(blank=True, help_text='Ej: igac.gov.co', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Fecha de expiración automática', null=True)),
                ('max_downloads', models.IntegerField(blank=True, help_text='Máximo de descargas permitidas', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('access_count', models.IntegerField(default=0)),
                ('download_count', models.IntegerField(default=0)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, help_text='Descripción interna (no visible al público)')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_share_links', to=settings.AUTH_USER_MODEL)),
                ('deactivated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deactivated_share_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Link Compartido',
                'verbose_name_plural': 'Links Compartidos',
                'db_table': 'share_links',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShareLinkAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('email_provided', models.EmailField(blank=True, max_length=254, null=True)),
                ('action', models.CharField(choices=[('view', 'Vió el archivo'), ('download', 'Descargó el archivo'), ('denied', 'Acceso denegado')], max_length=20)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('share_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='sharing.sharelink')),
            ],
            options={
                'verbose_name': 'Acceso a Link Compartido',
                'verbose_name_plural': 'Accesos a Links Compartidos',
                'db_table': 'share_link_accesses',
                'ordering': ['-accessed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='sharelink',
            index=models.Index(fields=['token'], name='share_links_token_5e7a57_idx'),
        ),
        migrations.AddIndex(
            model_name='sharelink',
            index=models.Index(fields=['created_by', 'is_active'], name='share_links_created_ed9b0d_idx'),
        ),
        migrations.AddIndex(
            model_name='sharelink',
            index=models.Index(fields=['expires_at'], name='share_links_expires_c51b58_idx'),
        ),
    ]
