# Generated by Django 4.2.16 on 2026-01-01 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trash', '0002_add_trash_item_to_sharelink'),
        ('sharing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharelink',
            name='trash_item',
            field=models.ForeignKey(blank=True, help_text='Si es un link a item de papelera', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='trash.trashitem'),
        ),
    ]
