# Generated by Django 5.2.8 on 2025-11-16 19:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Username')),
                ('first_name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=150, verbose_name='Apellido')),
                ('role', models.CharField(choices=[('consultation', 'Consulta'), ('consultation_edit', 'Consulta + Edición'), ('admin', 'Administrador'), ('superadmin', 'Super Administrador')], default='consultation', max_length=20, verbose_name='Rol')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('department', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dependencia')),
                ('position', models.CharField(blank=True, max_length=200, null=True, verbose_name='Cargo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Última IP de login')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField(help_text='Ruta del directorio favorito', verbose_name='Ruta')),
                ('name', models.CharField(help_text='Nombre para mostrar', max_length=255, verbose_name='Nombre personalizado')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('color', models.CharField(default='blue', help_text='Color para identificación visual', max_length=20, verbose_name='Color')),
                ('order', models.IntegerField(default=0, help_text='Orden de visualización', verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('access_count', models.IntegerField(default=0, verbose_name='Contador de accesos')),
                ('last_accessed', models.DateTimeField(blank=True, null=True, verbose_name='Último acceso')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Favorito',
                'verbose_name_plural': 'Favoritos',
                'ordering': ['order', '-access_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_path', models.TextField(help_text='Ruta desde la cual aplica el permiso', verbose_name='Ruta base')),
                ('can_read', models.BooleanField(default=True, verbose_name='Puede leer')),
                ('can_write', models.BooleanField(default=False, verbose_name='Puede escribir')),
                ('can_delete', models.BooleanField(default=False, verbose_name='Puede eliminar')),
                ('exempt_from_dictionary', models.BooleanField(default=False, help_text='Si está activado, no valida nombres contra el diccionario', verbose_name='Exento de diccionario')),
                ('edit_permission_level', models.CharField(blank=True, choices=[('upload_only', 'Solo Subir Archivos'), ('upload_own', 'Subir + Editar/Eliminar Propios'), ('upload_all', 'Subir + Editar/Eliminar Todos')], help_text='Solo aplica para usuarios con rol consultation_edit', max_length=20, null=True, verbose_name='Nivel de permiso de edición')),
                ('inheritance_mode', models.CharField(choices=[('total', 'Herencia Total'), ('blocked', 'Herencia con Bloqueos'), ('limited_depth', 'Rango Limitado de Profundidad')], default='total', help_text='Cómo se heredan permisos a subdirectorios', max_length=20, verbose_name='Modo de herencia')),
                ('blocked_paths', models.JSONField(blank=True, default=list, help_text='Lista de rutas bloqueadas cuando inheritance_mode=blocked', verbose_name='Rutas bloqueadas')),
                ('max_depth', models.IntegerField(blank=True, help_text='Niveles de profundidad cuando inheritance_mode=limited_depth', null=True, verbose_name='Profundidad máxima')),
                ('read_only_subdirs', models.JSONField(blank=True, default=list, help_text='Lista de subdirectorios donde solo puede leer (no escribir)', verbose_name='Subdirectorios solo lectura')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de otorgamiento')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de revocación')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('directory', models.ForeignKey(blank=True, help_text='Directorio al que aplica este permiso', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='files.directory', verbose_name='Directorio')),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permissions_granted', to=settings.AUTH_USER_MODEL, verbose_name='Otorgado por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Permiso de usuario',
                'verbose_name_plural': 'Permisos de usuario',
                'ordering': ['-granted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_user_email_6f2530_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='users_user_usernam_65d164_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='users_user_role_36d76d_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='users_user_is_acti_ddda02_idx'),
        ),
        migrations.AddIndex(
            model_name='userfavorite',
            index=models.Index(fields=['user', 'order'], name='users_userf_user_id_13355f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userfavorite',
            unique_together={('user', 'path')},
        ),
        migrations.AddIndex(
            model_name='userpermission',
            index=models.Index(fields=['user', 'is_active'], name='users_userp_user_id_eb3c30_idx'),
        ),
        migrations.AddIndex(
            model_name='userpermission',
            index=models.Index(fields=['base_path'], name='users_userp_base_pa_b1be71_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userpermission',
            unique_together={('user', 'base_path')},
        ),
    ]
