# Generated by Django 5.2.8 on 2025-11-17 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermission',
            name='can_create_directories',
            field=models.BooleanField(default=True, help_text='Si está en False, solo puede subir archivos pero no crear/renombrar directorios', verbose_name='Puede crear directorios'),
        ),
    ]
