# Generated by Django 5.2.8 on 2025-11-17 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_userpermission_directory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Token')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('expires_at', models.DateTimeField(verbose_name='Fecha de expiración')),
                ('used', models.BooleanField(default=False, verbose_name='Usado')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de uso')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Token de recuperación de contraseña',
                'verbose_name_plural': 'Tokens de recuperación de contraseña',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='users_passw_token_b56ca3_idx'), models.Index(fields=['user', 'used'], name='users_passw_user_id_5d315e_idx')],
            },
        ),
    ]
