# Generated by Django 5.2.8 on 2025-11-21 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_userpermission_directory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermission',
            name='expiration_notified_3days',
            field=models.BooleanField(default=False, help_text='Indica si se envió la notificación 3 días antes del vencimiento', verbose_name='Notificado 3 días antes'),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='expiration_notified_7days',
            field=models.BooleanField(default=False, help_text='Indica si se envió la notificación 7 días antes del vencimiento', verbose_name='Notificado 7 días antes'),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Fecha hasta la cual el permiso es válido. Si no se especifica, se asigna hasta el 31 de diciembre del año actual.', null=True, verbose_name='Fecha de vencimiento'),
        ),
        migrations.AddIndex(
            model_name='userpermission',
            index=models.Index(fields=['expires_at', 'is_active'], name='users_userp_expires_ccc28f_idx'),
        ),
    ]
