# Generated by Django 5.2.8 on 2025-11-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_permission_expiration_fields'),
    ]

    operations = [
        # Los campos 'directory' y 'read_only_subdirs' ya fueron eliminados en la migración 0003
        # No intentar eliminarlos de nuevo
        migrations.AddField(
            model_name='user',
            name='can_manage_dictionary',
            field=models.BooleanField(default=False, help_text='Si está activado, el usuario puede crear/editar/eliminar términos del diccionario', verbose_name='Puede gestionar diccionario'),
        ),
    ]
