# Generated by Django 5.2.8 on 2025-11-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_userpermission_directory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermission',
            name='read_only_paths',
            field=models.JSONField(blank=True, default=list, help_text='Lista de rutas donde solo puede leer/descargar cuando inheritance_mode=partial_write', verbose_name='Rutas de solo lectura'),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='inheritance_mode',
            field=models.CharField(choices=[('total', 'Herencia Total'), ('blocked', 'Herencia con Bloqueos'), ('limited_depth', 'Rango Limitado de Profundidad'), ('partial_write', 'Herencia Parcial con Restricciones de Escritura')], default='total', help_text='Cómo se heredan permisos a subdirectorios', max_length=20, verbose_name='Modo de herencia'),
        ),
    ]
