# Generated by Django 5.2.8 on 2025-11-25 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_userpermission_directory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermission',
            name='group_name',
            field=models.CharField(blank=True, help_text='Identificador de grupo para gestionar asignaciones masivas', max_length=200, null=True, verbose_name='Nombre de grupo'),
        ),
        migrations.AddIndex(
            model_name='userpermission',
            index=models.Index(fields=['group_name'], name='users_userp_group_n_dbe6f9_idx'),
        ),
    ]
