# Generated by Django 5.2.8 on 2025-11-26 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userpermission_group_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermission',
            name='authorized_by_email',
            field=models.EmailField(blank=True, help_text='Correo electrónico del líder que autorizó este permiso', max_length=254, null=True, verbose_name='Email de quien autoriza'),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='authorized_by_name',
            field=models.CharField(blank=True, help_text='Nombre completo del líder que autorizó este permiso', max_length=300, null=True, verbose_name='Nombre de quien autoriza'),
        ),
    ]
