# Generated by Django 4.2.16 on 2026-01-04 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_userpermission_directory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='exempt_from_name_length',
            field=models.BooleanField(default=False, help_text='Si está activado, el usuario puede exceder el límite de 30 caracteres en nombres', verbose_name='Exento de límite de nombre'),
        ),
        migrations.AddField(
            model_name='user',
            name='exempt_from_naming_rules',
            field=models.BooleanField(default=False, help_text='Si está activado, el usuario puede nombrar archivos/carpetas sin validación de diccionario ni IA', verbose_name='Exento de reglas de nombrado'),
        ),
        migrations.AddField(
            model_name='user',
            name='exempt_from_path_limit',
            field=models.BooleanField(default=False, help_text='Si está activado, el usuario puede exceder el límite de 260 caracteres en rutas', verbose_name='Exento de límite de ruta'),
        ),
        migrations.AddField(
            model_name='user',
            name='exemption_granted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de exención'),
        ),
        migrations.AddField(
            model_name='user',
            name='exemption_granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exemptions_granted', to=settings.AUTH_USER_MODEL, verbose_name='Exención otorgada por'),
        ),
        migrations.AddField(
            model_name='user',
            name='exemption_reason',
            field=models.TextField(blank=True, help_text='Justificación para las exenciones otorgadas', null=True, verbose_name='Razón de exención'),
        ),
    ]
