# Generated by Django 4.2.16 on 2026-01-04 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_add_naming_exemptions'),
    ]

    operations = [
    ]
