# Generated by Django 4.2.16 on 2026-01-04 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_fix_migration_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpermission',
            name='directory',
        ),
        migrations.RemoveField(
            model_name='userpermission',
            name='read_only_subdirs',
        ),
    ]
