# Generated by Django 5.2.8 on 2025-11-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField(db_index=True, unique=True, verbose_name='Ruta completa relativa')),
                ('name', models.CharField(max_length=500, verbose_name='Nombre del directorio')),
                ('depth', models.IntegerField(db_index=True, default=0, verbose_name='Nivel de profundidad')),
                ('created_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de creación')),
                ('modified_date', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Fecha de modificación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en sistema')),
                ('file_count', models.IntegerField(default=0, verbose_name='Cantidad de archivos directos')),
                ('subdir_count', models.IntegerField(default=0, verbose_name='Cantidad de subdirectorios directos')),
                ('total_size', models.BigIntegerField(default=0, verbose_name='Tamaño total en bytes')),
                ('indexed_at', models.DateTimeField(auto_now=True, verbose_name='Última indexación')),
                ('is_active', models.BooleanField(default=True, help_text='Si el directorio existe en NetApp', verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Directorio',
                'verbose_name_plural': 'Directorios',
                'ordering': ['path'],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField(db_index=True, unique=True, verbose_name='Ruta completa relativa')),
                ('name', models.TextField(verbose_name='Nombre de archivo')),
                ('extension', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Extensión')),
                ('size', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Tamaño en bytes')),
                ('modified_date', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Fecha de modificación')),
                ('created_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de creación')),
                ('md5_hash', models.CharField(blank=True, max_length=32, null=True, verbose_name='Hash MD5')),
                ('uploaded_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de subida')),
                ('modified_by_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha modificación por usuario')),
                ('indexed_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de indexación')),
            ],
            options={
                'verbose_name': 'Archivo',
                'verbose_name_plural': 'Archivos',
                'ordering': ['path'],
            },
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_files', models.BigIntegerField(default=0, verbose_name='Total de archivos')),
                ('total_directories', models.BigIntegerField(default=0, verbose_name='Total de directorios')),
                ('total_size', models.BigIntegerField(default=0, verbose_name='Tamaño total en bytes')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Estadística',
                'verbose_name_plural': 'Estadísticas',
            },
        ),
    ]
