# Generated by Django 5.2.8 on 2025-11-16 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_directories', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='directory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='files.directory', verbose_name='Directorio padre'),
        ),
        migrations.AddField(
            model_name='file',
            name='directory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='files.directory', verbose_name='Directorio padre'),
        ),
        migrations.AddField(
            model_name='file',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_files', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='file',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL, verbose_name='Subido por'),
        ),
        migrations.AddIndex(
            model_name='directory',
            index=models.Index(fields=['path'], name='files_direc_path_dd870d_idx'),
        ),
        migrations.AddIndex(
            model_name='directory',
            index=models.Index(fields=['parent'], name='files_direc_parent__bd6a1a_idx'),
        ),
        migrations.AddIndex(
            model_name='directory',
            index=models.Index(fields=['depth'], name='files_direc_depth_b0f2e4_idx'),
        ),
        migrations.AddIndex(
            model_name='directory',
            index=models.Index(fields=['modified_date'], name='files_direc_modifie_add9ec_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['path'], name='files_file_path_5ff15e_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['name'], name='files_file_name_350fdc_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['extension'], name='files_file_extensi_c10850_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['size'], name='files_file_size_6009e9_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['modified_date'], name='files_file_modifie_1bd673_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['directory', 'name'], name='files_file_directo_3daae7_idx'),
        ),
    ]
