# Generated by Django 4.2.16 on 2026-01-07 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectoryColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directory_path', models.TextField(db_index=True, verbose_name='Ruta del directorio')),
                ('color', models.CharField(default='#3B82F6', max_length=9, verbose_name='Color')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directory_colors', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Color de Directorio',
                'verbose_name_plural': 'Colores de Directorios',
                'indexes': [models.Index(fields=['user', 'directory_path'], name='files_direc_user_id_8408e0_idx')],
                'unique_together': {('user', 'directory_path')},
            },
        ),
    ]
