# Generated by Django 5.2.8 on 2025-11-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150, verbose_name='Nombre de usuario')),
                ('user_role', models.CharField(max_length=20, verbose_name='Rol del usuario')),
                ('action', models.CharField(choices=[('upload', 'Subir Archivo'), ('download', 'Descargar'), ('delete', 'Eliminar'), ('rename', 'Renombrar'), ('create_folder', 'Crear Carpeta'), ('move', 'Mover'), ('copy', 'Copiar'), ('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión')], db_index=True, max_length=20, verbose_name='Acción')),
                ('target_path', models.TextField(verbose_name='Ruta objetivo')),
                ('target_name', models.TextField(blank=True, null=True, verbose_name='Nombre del archivo/directorio')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='Tamaño del archivo')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Detalles adicionales')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('success', models.BooleanField(default=True, verbose_name='Éxito')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Mensaje de error')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha y hora')),
            ],
            options={
                'verbose_name': 'Registro de auditoría',
                'verbose_name_plural': 'Registros de auditoría',
                'ordering': ['-timestamp'],
            },
        ),
    ]
