# Generated by Django 5.2.8 on 2025-11-18 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_path', models.TextField(verbose_name='Ruta base')),
                ('action', models.CharField(choices=[('granted', 'Permiso Otorgado'), ('revoked', 'Permiso Revocado'), ('modified', 'Permiso Modificado')], db_index=True, max_length=20, verbose_name='Acción')),
                ('permission_type', models.CharField(blank=True, choices=[('read', 'Lectura'), ('write', 'Escritura'), ('delete', 'Eliminación'), ('create_directories', 'Crear Directorios')], max_length=30, null=True, verbose_name='Tipo de permiso')),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de cambio')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Detalles adicionales')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_changes_made', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_audits', to=settings.AUTH_USER_MODEL, verbose_name='Usuario afectado')),
            ],
            options={
                'verbose_name': 'Auditoría de permisos',
                'verbose_name_plural': 'Auditorías de permisos',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['user', 'changed_at'], name='audit_permi_user_id_0a6e72_idx'), models.Index(fields=['action', 'changed_at'], name='audit_permi_action_66b542_idx'), models.Index(fields=['changed_at'], name='audit_permi_changed_f905ad_idx')],
            },
        ),
        migrations.CreateModel(
            name='ZipAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_path', models.TextField(db_index=True, verbose_name='Ruta del archivo ZIP')),
                ('zip_name', models.CharField(max_length=500, verbose_name='Nombre del ZIP')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de análisis')),
                ('contained_files', models.JSONField(default=list, verbose_name='Archivos contenidos')),
                ('total_files', models.IntegerField(default=0, verbose_name='Total de archivos')),
                ('total_size', models.BigIntegerField(default=0, verbose_name='Tamaño total (bytes)')),
                ('zip_size', models.BigIntegerField(blank=True, null=True, verbose_name='Tamaño del ZIP (bytes)')),
                ('compression_ratio', models.FloatField(blank=True, null=True, verbose_name='Ratio de compresión')),
                ('analyzed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zip_analyses', to=settings.AUTH_USER_MODEL, verbose_name='Analizado por')),
            ],
            options={
                'verbose_name': 'Análisis de ZIP',
                'verbose_name_plural': 'Análisis de ZIPs',
                'ordering': ['-analyzed_at'],
                'indexes': [models.Index(fields=['zip_path', 'analyzed_at'], name='audit_zipan_zip_pat_509db3_idx')],
            },
        ),
    ]
