# Generated by Django 4.2.16 on 2026-01-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_permissionaudit_zipanalysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('upload', 'Subir Archivo'), ('download', 'Descargar'), ('delete', 'Eliminar'), ('rename', 'Renombrar'), ('create_folder', 'Crear Carpeta'), ('move', 'Mover'), ('copy', 'Copiar'), ('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('smart_rename', 'Renombrado Inteligente'), ('smart_rename_batch', 'Renombrado Batch'), ('update_exemptions', 'Actualizar Exenciones')], db_index=True, max_length=50, verbose_name='Acción'),
        ),
        migrations.AlterField(
            model_name='permissionaudit',
            name='action',
            field=models.CharField(choices=[('granted', 'Permiso Otorgado'), ('revoked', 'Permiso Revocado'), ('modified', 'Permiso Modificado')], db_index=True, max_length=50, verbose_name='Acción'),
        ),
    ]
